# application.yml

server:
  port: 8085 # or your preferred port

spring:
  application:
    name: isp-server-app
dns:
  server:
    url: http://localhost:8081
 
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false