# application.yml

server:
  port: 8051 # or your preferred port

spring:
  application:
    name: dfs-b
  service-discovery-app: http://localhost:8761/eureka/apps

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true # Optiona